stages:
  - build
  - deploy

build_homol:
  stage: build
  image: node:16-alpine
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration=homol --output-path=dist/homol
  artifacts:
    paths:
      - dist/homol
  only:
    - deploy

build_production:
  stage: build
  image: node:16-alpine
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration=production --output-path=dist/prod
  artifacts:
    paths:
      - dist/prod
  only:
    - deploy-prod

deploy_homol:
  stage: deploy
  environment: homol
  image: google/cloud-sdk:alpine
  dependencies:
    - build_homol
  script:
    - cd dist/homol
    - sh set-gcloud-servicename.sh
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_GCLOUD_STAG.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_GCLOUD_STAG.json
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml --verbosity=debug
  only:
    - deploy

deploy_production:
  stage: deploy
  environment: prod
  image: google/cloud-sdk:alpine
  dependencies:
    - build_production
  script:
    - cd dist/prod
    - sh set-gcloud-servicename.sh
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_GCLOUD_STAG.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_GCLOUD_STAG.json
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml --verbosity=debug
  only:
    - deploy-prod

after_script:
  - rm /tmp/$CI_PIPELINE_GCLOUD_STAG.json